kind: wasmer.io/App.v0
name: tsn-rpc-gateway
owner: aurionexchange
package: .
annotations:
  anybuild.run/config:
    commands:
      start: node --env-file-if-exists=.env server.mjs
    edgejs_enable: true
    edgejs_precompile: true
    name: out
    node_install_inputs:
    - package.json
    node_package_manager: npm
    node_package_name: '@trustlink/tsn-rpc-gateway'
    node_remove_native_binaries: true
    node_server: node
  anybuild.run/provider: node
  anybuild.run/version: 0.27.2
  wasmer.io/version: 7.2.1
app_id: da_KN4IZtyU4JMJ
